[storage]
type = "local"
path = "/tmp/data"

[server]
host = "0.0.0.0"
port = 8080
base_url = "https://twoja-appka.onrender.com"

[[feeds]]
url = "https://www.youtube.com/channel/UCO6_hwMtQZ0SLElfDMaqJGQ"
name = "kanal1"
format = "mp4"
quality = "best"
